### ISSUE TITLE
Create template issue to manage the migration of each repo

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/admin-project-board-migration#1]
### Overview
We need to manage all the repo migrations so that we don't lose data and that we hit the deadline for migration (August 23rd, 2024)

### Action Items
 - [x] Create a template
 - [x] Add labels for project names and status
 - [x] Define the default labels that will be on the template
 - [x] Make missing labels
 - [x] Add draft label

### Resources/Instructions
- Actions wiki: https://github.com/hackforla/admin-project-board-migration/wiki
- Migration Issue Template: https://github.com/hackforla/product-management/wiki/GitHub-Project-Board-Migration-Issue

**Comment by ExperimentsInHonesty** [comment]
# Draft

###
Title: [PROJECT INITIALS: [REPO]: [Board Name]:  Other

### Overview
We need to migrate the GitHub project boards on this repo so that we don't lose any content.

#### Details
Content includes
- Cards (The new project boards don't support cards)
- Merging multiple boards into one board with different views
- capturing closed boards

### Action Items

#### Add initial content to Resources section
- [ ] Add Project Initials
- [ ] Add the link to repo
- [ ] Add a link to project board(s) classic
- [ ] Add a link to project board new if it already exists
- [ ] Add the Evaluate label

#### Evaluate
Remove actions * that do not need to be taken in this section (see Resource 1.03 for more detail)
- [ ] Cards to copy *
- [ ] Separate boards *
- [ ] Issue not on board *
- [ ] Migrate
- [ ] Customize (optional)
- [ ] Close out Migration

### Resources/Instructions

#### Resources for creating this issue
- Project Initials
- 1.02 Repo:
- 1.03 Classic Project Board(s):
   - [Name]
   - [Name]
- 1.04 Actions wiki: https://github.com/hackforla/admin-project-board-migration/wiki
- 1.05 New Project Board:  [Name]

#### Resources created while working on this issue
- 2.01 Migration Issue
- 2.02 New Project Board:  [Name]

**Comment by ExperimentsInHonesty** [comment]
# Draft

### Overview
We need to migrate the GitHub project boards on this repo so that we don't lose any content.

#### Details
Content includes
- Cards (The new project boards don't support cards)
- Merging multiple boards into one board with different views
- capturing closed boards

### Action Items

#### Add initial content to Resources section
- [ ] Add Project Initials (1.01)
- [ ] Add the link to repo (1.02)
- [ ] Add a link to project board(s) classic open (1.03), or write none, if there aren't any
- [ ] Add a link to project board(s) classic closed (1.04), or write none, if there aren't any
- [ ] Add a link to project board new if it already exists (1.05), or write none, if there isin't one linked
- [ ] Add the label for the project name (e.g., `Access the Data`) and remove the `project: missing label`
- [ ] Add the Evaluate label and remove the draft label
- [ ] Add the milestone `Migration`
- [ ] Delete this section

#### Evaluate
- [ ] Add strike-through to actions * that do not need to be taken in this section (see Resource 1.03 for more detail)
   - Cards to copy *
   - Multiple Boards Migration *
   - Single Board Migration *
   - Issues not on board *
- [ ] Add the labels for all the actions that need to be completed
- [ ] Remove the `evaluate` label
- [ ] Add the next label
   - [ ] If the Cards to copy has been strike-through, add the `migrate` label and check off/skip the Prepare section 
   - [ ] If the Cards to copy has not been strike-through, add the `prepare` label 

#### Prepare
Do the following actions unless strike though indicated above by going to the wiki (1.06) and following the instructions
- [ ] Cards to copy
- [ ] Remove the `prepare` label and add the `migrate` label

#### Migrate
Do the following actions unless strike though indicated above by going to the wiki (1.06) and following the instructions
- [ ] Boards Migration
   - [ ] Multiple Boards Migration
   - [ ] Single Board Migration
- [ ] Remove the `migrate` label and add the `cleanup` label

#### Cleanup
Do the following actions by going to the wiki (1.06) and following the instructions
   - [ ] Issues not on board
   - [ ] Customize (optional)
   - [ ] Close out Migration


### Resources/Instructions

#### Resources for creating this issue
- Project Initials:
- 1.02 Repo:
- 1.03 Classic Project Board(s) open:
   - [Name]
   - [Name]
- 1.04 Classic Project Board(s) closed:
   - [Name]
   - [Name]
- 1.05 New Project Board: [Name] 
- 1.06 Actions wiki: https://github.com/hackforla/admin-project-board-migration/wiki

#### Resources created while working on this issue
- 2.01 Migration Issue
- 2.02 New Project Board:  [Name]
